### ISSUE TITLE
Failed to build bagua-core

### ISSUE THREAD

**Issue by shiyf369** [BaguaSys/bagua#176]
Hello, when I use "pip3 install bagua" to install bagua, it failed to build bagua-core, but I have installed "cmake" and it can be used normally.
Could you help to give some suggestions? Thank you

```
`    cargo:rustc-link-lib=stdc++
    running: "cmake" "/tmp/pip-install-mx1rif45/bagua-core_59d5f79d51de45dcaed33940f487d58d/bagua-core-internal/third_party/Aluminum" "-DALUMINUM_ENABLE_NCCL=YES" "-DCUB_INCLUDE_PATH=/tmp/pip-install-mx1rif45/bagua-core_59d5f79d51de45dcaed33940f487d58d/bagua-core-internal/third_party/cub-1.8.0" "-DNCCL_LIBRARY=/tmp/pip-install-mx1rif45/bagua-core_59d5f79d51de45dcaed33940f487d58d/bagua-core-internal/../python/bagua_core/.data/lib/libnccl.so" "-DNCCL_INCLUDE_PATH=/tmp/pip-install-mx1rif45/bagua-core_59d5f79d51de45dcaed33940f487d58d/bagua-core-internal/../python/bagua_core/.data/include" "-DBUILD_SHARED_LIBS=off" "-DCMAKE_INSTALL_PREFIX=/tmp/pip-install-mx1rif45/bagua-core_59d5f79d51de45dcaed33940f487d58d/bagua-core-internal/../python/bagua_core/.data" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"

    --- stderr
    thread 'main' panicked at '
    failed to execute command: No such file or directory (os error 2)
    is `cmake` not installed?

    build script failed, must exit now', /home/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.45/src/lib.rs:894:5
    stack backtrace:
       0:     0x56105bac143c - std::backtrace_rs::backtrace::libunwind::trace::h7f0f727c679b121e
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
       1:     0x56105bac143c - std::backtrace_rs::backtrace::trace_unsynchronized::h27b8207adc787597
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
       2:     0x56105bac143c - std::sys_common::backtrace::_print_fmt::h18c4a15687f3f453
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:67:5
       3:     0x56105bac143c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7077f94cc0b2a619
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:46:22
       4:     0x56105baff95f - core::fmt::write::hd1fcbdc89ccede50
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/fmt/mod.rs:1096:17
       5:     0x56105bac0966 - std::io::Write::write_fmt::h3030f95a96ab63e0
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/io/mod.rs:1568:15
       6:     0x56105bad5d85 - std::sys_common::backtrace::_print::hce920b6e4ede72f2
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:49:5
       7:     0x56105bad5d85 - std::sys_common::backtrace::print::h63694f3a744810f6
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:36:9
       8:     0x56105bad5d85 - std::panicking::default_hook::{{closure}}::h2f22ad38e825d5e1
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:208:50
       9:     0x56105bad5953 - std::panicking::default_hook::hc0998dccd7f968a3
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:225:9
      10:     0x56105bad63b5 - std::panicking::rust_panic_with_hook::h618d5ded1dbe5ea3
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:591:17
      11:     0x56105bac1c57 - std::panicking::begin_panic_handler::{{closure}}::h64f3a351a9df3931
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:497:13
      12:     0x56105bac159c - std::sys_common::backtrace::__rust_end_short_backtrace::hf7a8c7450479e920
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:141:18
      13:     0x56105bad5f62 - rust_begin_unwind
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:493:5
      14:     0x56105bad5f1b - std::panicking::begin_panic_fmt::hebe0559d9879d61b
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:435:5
      15:     0x56105b9fe46e - cmake::fail::h65c3b59aa0a41805
      16:     0x56105b9fdc49 - cmake::run::hadada146119041a3
      17:     0x56105b9fa357 - cmake::Config::build::hf378bf25dc44c5d0
      18:     0x56105b5ad7f7 - build_script_build::main::h0418d648b0aad2b0
      19:     0x56105b5b2a83 - core::ops::function::FnOnce::call_once::he46fc27bc56f6eca
      20:     0x56105b5b4d59 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9b9f3182c5c3e1d2
      21:     0x56105b5b2919 - std::rt::lang_start::{{closure}}::h64ba8d1efb9a0730
      22:     0x56105bad676a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hacf21ab16c4aa1f7
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/ops/function.rs:259:13
      23:     0x56105bad676a - std::panicking::try::do_call::h002bd74c4d814788
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:379:40
      24:     0x56105bad676a - std::panicking::try::hae0844c0aa736d3d
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:343:19
      25:     0x56105bad676a - std::panic::catch_unwind::hec4fe4ae39575e8f
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panic.rs:431:14
      26:     0x56105bad676a - std::rt::lang_start_internal::h024664467cde3297
                                   at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/rt.rs:51:25
      27:     0x56105b5b28f8 - std::rt::lang_start::h12b74a027a8f19a5
      28:     0x56105b5af17b - main
      29:     0x7f1f3f9b1bf7 - __libc_start_main
      30:     0x56105b5ac93a - _start
      31:                0x0 - <unknown>
  error: cargo failed with code: 101

  ----------------------------------------
  ERROR: Failed building wheel for bagua-core
  Building wheel for py-cpuinfo (setup.py) ... done
  Created wheel for py-cpuinfo: filename=py_cpuinfo-8.0.0-py3-none-any.whl size=22245 sha256=9aae33f52f9f51373e1b282ea5ba6efa6d0d181da7f042b5ff2947178df78224
  Stored in directory: /tmp/pip-ephem-wheel-cache-n50tp78b/wheels/57/cb/6d/bab2257f26c5be4a96ff65c3d2a7122c96529b73773ee37f36
Successfully built bagua py-cpuinfo
Failed to build bagua-core
ERROR: Could not build wheels for bagua-core which use PEP 517 and cannot be installed directly`
```

**Comment by NOBLES5E** [comment]
Thanks. Which Linux distribution are you using? It will be great if you can provide a Dockerfile to reproduce the error, so that we can investigate. It's a bit hard to find the root cause just from the error.

The `cmake` not found error can also come from some arguments of `cmake` (like `"/tmp/pip-install-mx1rif45/bagua-core_59d5f79d51de45dcaed33940f487d58d/bagua-core-internal/third_party/Aluminum"`, and the `/usr/bin/cc` in `"-DCMAKE_ASM_COMPILER=/usr/bin/cc"`) do not exist on your filesystem.

**Comment by shiyf369** [comment]
I use “Ubuntu 18.04.4 LTS”， "/usr/bin/c++" and "/usr/bin/cc" can be used normally.

**Comment by NOBLES5E** [comment]
Have you tried the official installation script [here](https://github.com/BaguaSys/bagua/blob/master/install.sh)?

**Comment by shiyf369** [comment]
thanks, I will try to use dockerfile
