### ISSUE TITLE
安装bagua失败

### ISSUE THREAD

**Issue by qiuyang163** [BaguaSys/bagua#584]
CentOS release 6.3 (Final)
cmake version 3.15.4
cuda 10.2
python 3.6.5

error info:
Building wheels for collected packages: bagua-core
  Building wheel for bagua-core (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/users/qiuyang05/bagua/pyenv_poros/bin/python3 /home/users/qiuyang05/bagua/pyenv_poros/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpfba3jbe2
       cwd: /tmp/pip-install-s89j4fy4/bagua-core_e859c25dc60f4aaf87aa92e7f3c53d15
  Complete output (75 lines):
  /tmp/pip-build-env-x33xel5w/overlay/lib/python3.6/site-packages/setuptools/dist.py:726: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
    % (opt, underscore_opt)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/bagua_core
  copying python/bagua_core/__init__.py -> build/lib.linux-x86_64-3.6/bagua_core
  copying python/bagua_core/_environment.py -> build/lib.linux-x86_64-3.6/bagua_core
  copying python/bagua_core/version.py -> build/lib.linux-x86_64-3.6/bagua_core
  running build_ext
  running build_rust
      Updating crates.io index
  warning: spurious network error (2 tries remaining): failed to connect to github.com: Connection timed out; class=Os (2)
  warning: spurious network error (1 tries remaining): failed to connect to github.com: Connection timed out; class=Os (2)
  error: failed to get `base64` as a dependency of package `bagua-core-internal v0.1.2 (/tmp/pip-install-s89j4fy4/bagua-core_e859c25dc60f4aaf87aa92e7f3c53d15/bagua-core-internal)`

  Caused by:
    failed to fetch `https://github.com/rust-lang/crates.io-index`

  Caused by:
    failed to connect to github.com: Connection timed out; class=Os (2)
  Traceback (most recent call last):
    File "/home/users/qiuyang05/bagua/pyenv_poros/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/users/qiuyang05/bagua/pyenv_poros/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/users/qiuyang05/bagua/pyenv_poros/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-x33xel5w/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 231, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-x33xel5w/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-x33xel5w/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 198, in <module>
      zip_safe=False,
    File "/tmp/pip-build-env-x33xel5w/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/users/qiuyang05/bagua/pyenv_poros/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/users/qiuyang05/bagua/pyenv_poros/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/users/qiuyang05/bagua/pyenv_poros/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-x33xel5w/overlay/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/users/qiuyang05/bagua/pyenv_poros/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/users/qiuyang05/bagua/pyenv_poros/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/users/qiuyang05/bagua/pyenv_poros/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/users/qiuyang05/bagua/pyenv_poros/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/users/qiuyang05/bagua/pyenv_poros/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-x33xel5w/overlay/lib/python3.6/site-packages/setuptools_rust/setuptools_ext.py", line 132, in run
      build_rust.run()
    File "/tmp/pip-build-env-x33xel5w/overlay/lib/python3.6/site-packages/setuptools_rust/command.py", line 101, in run
      self.run_for_extension(ext)
    File "/tmp/pip-build-env-x33xel5w/overlay/lib/python3.6/site-packages/setuptools_rust/build.py", line 108, in run_for_extension
      dylib_paths = self.build_extension(ext, self.target)
    File "/tmp/pip-build-env-x33xel5w/overlay/lib/python3.6/site-packages/setuptools_rust/build.py", line 139, in build_extension
      target_dir = _base_cargo_target_dir(ext)
    File "/tmp/pip-build-env-x33xel5w/overlay/lib/python3.6/site-packages/setuptools_rust/build.py", line 673, in _base_cargo_target_dir
      target_directory = ext._metadata()["target_directory"]
    File "/tmp/pip-build-env-x33xel5w/overlay/lib/python3.6/site-packages/setuptools_rust/extension.py", line 200, in _metadata
      self._cargo_metadata = json.loads(subprocess.check_output(metadata_command))
    File "/home/users/qiuyang05/bagua/pyenv_poros/lib/python3.6/subprocess.py", line 336, in check_output
      **kwargs).stdout
    File "/home/users/qiuyang05/bagua/pyenv_poros/lib/python3.6/subprocess.py", line 418, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'bagua-core-py/Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.
  ----------------------------------------
  ERROR: Failed building wheel for bagua-core
Failed to build bagua-core
ERROR: Could not build wheels for bagua-core, which is required to install pyproject.toml-based projects

**Comment by wangraying** [comment]
Bagua requires to use python >=3.7 now, would you please upgrade your python and try to install the pre-compiled version?
https://tutorials.baguasys.com/installation#installing-bagua

You may also try to manually install from source using the commands [here](https://github.com/BaguaSys/bagua/blob/master/install_master.sh ) .

**Comment by wangraying** [comment]
I'll close this issue if no more problems arise.
